#!/bin/sh
mig=/Users/jonbjornstad/catalyst/projects/RetreatCenter/migration
cd $mig

rm -rf new
echo ftp
ftp www.mountmadonna.org <<EOC
hash
get dmpfile.tar.Z
quit
EOC
echo uncompress
uncompress -f dmpfile.tar.Z
echo untar
tar xvf dmpfile.tar

./loadall
