#!/bin/sh
cd /Users/jonbjornstad/catalyst/projects/RetreatCenter/migration
rm -rf new
echo ftp
ftp www.mountmadonna.org <<EOC >/tmp/dump.out 2>&1
get dmpfile.tar.Z
quit
EOC
echo uncompress
uncompress -f dmpfile.tar.Z
echo untar
tar xf dmpfile.tar >/tmp/dump.out 2>&1
echo loading
sqlite3 retreatcenter.db <mkpeople
sqlite3 retreatcenter.db <mkmisc
sqlite3 retreatcenter.db <mkprog
sqlite3 retreatcenter.db <mkrep
sqlite3 retreatcenter.db <mkusers
sqlite3 retreatcenter.db <mkmember
sqlite3 retreatcenter.db <mkreg
load.pl
loadstr.pl
loadprog.pl
cp retreatcenter.db ..
