#!/usr/bin/perl
use strict;
use warnings;
use DBI;

sub nsquish {
    my ($addr1, $addr2, $zip) = @_;
    my $s = uc($addr1 . $addr2 . $zip);
    my $n = $s;
    $n =~ s{\D}{}g;
    $s =~ s{[^A-Z]}{}g;
    $s = substr($s, 0, 3);
    return ($n . $s);
}

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";
my $find_affil = $dbh->prepare("
    select id
    from affils
    where descrip like '%temple%guest%'
");
my $ins_affil = $dbh->prepare("
    insert into affil_people
    (a_id, p_id)
    values (?, ?);
");
my $find_paffil = $dbh->prepare("
    select a_id
    from affil_people
    where a_id = ? and p_id = ?
");
$find_affil->execute();
my ($temple_id) = $find_affil->fetchrow_array();
my $find_sth = $dbh->prepare("
    select id
    from people
    where first = ? and last = ?
");

# what about mailing/sharing preferences?
#
my $ins_sth = $dbh->prepare("
    insert into people
    (first, last, email, tel_cell, addr1, addr2,
     city, st_prov, zip_post,
     e_mailings, snail_mailings,
     mmi_e_mailings, mmi_snail_mailings,
    )
    values
    (?, ?, ?, ?, ?, ?, ?, ?, ?,
     'yes', '',
     'yes', '');
");
my $upd_sth = $dbh->prepare("
    update people
    set
    email = ?,
    tel_cell = ?,
    addr1 = ?,
    addr2 = ?,
    city = ?,
    st_prov = ?,
    zip_post = ?,
    e_mailings = 'yes',
    snail_mailings = '',
    mmi_e_mailings = 'yes',
    mmi_snail_mailings = '',
    share_mailings = 'yes',
    inactive = '',
    date_entrd = '20100904',
    akey = ?
    where 
    id = ?
");

open my $tmpl, "<", "temple.txt"
    or die "cannot open temple.txt: $!\n";
my $n = 0;
TMPL:
while (my $line = <$tmpl>) {
    chomp $line;
    my @flds = split m{\|}, $line;
    @flds = @flds[0..2, 5..10];
    if ($flds[3] =~ m{\d{10}}) {
        $flds[3] =~ s{(\d{3})(\d{3})(\d{4})}{$1-$2-$3};
    }
    $find_sth->execute(@flds[0, 1]) or die "no exec find";
    my ($id) = $find_sth->fetchrow_array();
    if ($id) {
        $upd_sth->execute(@flds[2 .. 8],
                          nsquish(@flds[4, 5, 8]),      # akey
                                            # forgot it for inserts
                                            # only a one time thing so ok?
                          $id) or die "no exec upd";
    }
    else {
        $ins_sth->execute(@flds) or die "no exec ins";
        $id = $dbh->last_insert_id(undef, undef, undef, undef);
    }
    $find_paffil->execute($temple_id, $id);
    my ($already_a_id) = $find_paffil->fetchrow_array();
    if (! $already_a_id) {
        $ins_affil->execute($temple_id, $id);
    }
    ++$n;
}
close $tmpl;
