#!/usr/bin/perl
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";

open my $ppl, "<", "mem/people.txt"
    or die "*** no people.txt\n";
my $sql = "select last, first, addr1, addr2, city, st_prov, zip_post, date_updat from people where id = ?";
my $sth = $dbh->prepare($sql) or die "oops1\n";
while (<$ppl>) {
    chomp;
    my ($id, $last, $first, $addr1, $addr2, $city, $state, $zip, $upd) = (split /\|/, $_, -1)[15, 0, 1, 3 .. 7, 18];
    $sth->execute($id);
    my ($l, $f, $a1, $a2, $c, $s, $z, $up) = $sth->fetchrow_array();
    if (   $l  ne $last
        || $f  ne $first
        || $a1 ne $addr1
        || $a2 ne $addr2
        || $c  ne $city
        || $s  ne $state
        || $z  ne $zip
    ) {
        print "$id\tnreg\t$first, $last, $addr1, $addr2, ",
              "$city, $state, $zip, $upd\n",
              "\tmlist\t$f, $l, $a1, $a2, $c, ",
              "$s, $z, $up\n";
    }
}
close $ppl;
undef $sth;
print "Loading memberships ... continue? ";
my $ans = <STDIN>;
if ($ans !~ m{^y}i) {
    exit;
}

open my $gp, "<", "gurupurnima.txt"
    or die "no gurupurnima.txt: $!\n";
my $gp_id = <$gp>;
chomp $gp_id;
close $gp;

my $search_gp = $dbh->prepare("
    select *
    from affil_people
    where a_id = ?
      and p_id = ?
") or die "no search";
my $ins_gp = $dbh->prepare("
    insert into affil_people
    values (?, ?)
") or die ("no ins_gp");

for my $tbl (qw/ member spons_hist night_hist /) {
    $dbh->do("delete from $tbl");
    my $q = "?,?,?,?,?,?,?,?";
    $q .= ",?" if $tbl eq 'member';
    my $sql = "insert into $tbl values ($q)";
    my $sth = $dbh->prepare($sql) or die "oops2 $tbl\n";
    open my $mem, "<", "mem/$tbl.txt" or die "$tbl.txt\n";
    while (<$mem>) {
        chomp;
        my @flds = split /\|/, $_, -1;
        my $person_id = $flds[1];
        if ($tbl =~ m{hist$}) {     # one time
            $flds[-1] =~ s{:}{};
        }
        $sth->execute(@flds);
        # make sure the person has guru purnima affil.
        $search_gp->execute($gp_id, $person_id);
        if (my ($x, $y) = $search_gp->fetchrow_array()) {
            # okay
        }
        else {
            $ins_gp->execute($gp_id, $person_id);
        }
    }
    close $mem;
}
