#!/bin/sh
if [ `whoami` = 'jonbjornstad' ]
then
    db='sqlite3 retreatcenter.db'
    export DBI_DSN="dbi:sqlite:retreatcenter.db"
else
    db='mysql -u sahadev -pJonB2458 reg2'
    export DBI_DSN="dbi:mysql:reg2"
fi

echo creating tables
$db <mkpeople
$db <mkmisc
$db <mkprog
$db <mkrep
$db <mkusers
$db <mkmember
$db <mkreg

echo strings, affils
loadstr
loadaf

echo clearing images
cd ../root/static/images
rm -f lo* lth* lb* po* pth* pb*
cd $mig

echo people
loadpeople
echo leaders, canpol, housecost, programs
loadprog f89
echo reg
loadreg  f89

cp retreatcenter.db ..
