#!/usr/bin/perl
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";
$dbh->do("delete from deposit");
#
#  id
#  user_id
#  date_start
#  date_end
#  time
#  cash
#  chk
#  credit
#  source
#
my $d_sql = "insert into deposit
values (
    ?, 2, ?, ?, '1700', ?, ?, ?, 'mmc'
)
";
my $d_sth = $dbh->prepare($d_sql) or die "no prep deposit insert\n";

my $next_deposit_id = 1;
open my $in, "<", "new/deposit.txt"
    or die "no new/deposit: $!\n";
#
#  date_start	01/01/1992
#  date_end	07/31/1992
#  cash	565
#  check	4439
#  credit	0
#
my %hash = ();
while (<$in>) {
    s{\r?\n$}{};
    my ($k, $v) = split m{\t};
    $v =~ s{^\s*|\s*$}{}g;
    $hash{$k} = $v;
    if ($k eq 'credit') {
        for ($hash{date_start}, $hash{date_end}) {
            s{(..)/(..)/(....)}{$3$1$2};
        }
        $d_sth->execute($next_deposit_id++,
                        $hash{date_start},
                        $hash{date_end},
                        $hash{cash},
                        $hash{check},
                        $hash{credit});
        %hash = ();
    }
}
close $in;
