#!/usr/bin/perl
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";
$dbh->do("delete from string");
my $sth = $dbh->prepare("insert into string values (?, ?);");

open my $strs, "<", "strings.txt"
    or die "cannot open strings.txt: $!\n";
my ($key, $value);
while (<$strs>) {
    next if m{^#} || m{^\s*$};
    chomp;
    ($key, $value) = m{^\s*(\S+)\s+(.*)$};
    $sth->execute($key, $value);
}
close $strs;

use lib "../lib";
use Date::Simple qw/
    today
/;
# special case
$sth->execute('last_deposit_date', today()->as_d8());
