#!/usr/bin/perl
use strict;
use warnings;
use DBI;
my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";

my $sth = $dbh->prepare("select id, name from rental");
my %rent_id;
$sth->execute();
while (my ($id, $name) = $sth->fetchrow_array()) {
    $rent_id{$name} = $id;
}
$sth = $dbh->prepare("select id, name from program");
my %prog_id;
$sth->execute();
while (my ($id, $name) = $sth->fetchrow_array()) {
    $prog_id{$name} = $id;
}
$sth = $dbh->prepare("select id, name from event");
my %event_id;
$sth->execute();
while (my ($id, $name) = $sth->fetchrow_array()) {
    $event_id{$name} = $id;
}

$sth = $dbh->prepare("insert into booking values (?,?,?,?,?,?,?,?);");

open my $meet, "<", "meet/meet.txt"
    or die "cannot open meet/meet.txt: $!\n";
while (<$meet>) {
    chomp;
    my ($name, $id, $meet_id, $rental_id, $program_id, $event_id, @flds)
        = split m{\|}, $_, -1;
    if ($rental_id) {
        if (exists $rent_id{$name}) {
            $rental_id = $rent_id{$name};
        }
        else {
            print "no id for rental '$name'\n";
            next;
        }
    }
    elsif ($program_id) {
        if (exists $prog_id{$name}) {
            $program_id = $prog_id{$name};
        }
        else {
            print "no id for program '$name'\n";
            next;
        }
    }
    elsif ($event_id) {
        if (exists $event_id{$name}) {
            $event_id = $event_id{$name};
        }
        else {
            print "no id for event '$name'\n";
            next;
        }
    }
    $sth->execute($id, $meet_id, $rental_id, $program_id, $event_id, @flds);
}
close $meet;
