#!/usr/bin/perl
use strict;
use warnings;
use DBI;
use Getopt::Easy;
use lib "../lib";
use Date::Simple qw/date/;

get_options("s-single");

my @seasons;
my $p = shift @ARGV;
while ($p ne 's08') {
    push @seasons, $p;
    last if $O{single};
    if ($p =~ m{^s}) {
        $p =~ s{s}{f};
    }
    else {
        my ($yr) = $p =~ m{(\d+)};
        $yr = ($yr + 1) % 100;
        $p = 's' . sprintf("%02d", $yr);
    }
}
push @seasons, 'cur' unless $O{single};

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";
$dbh->do("delete from rental");

=comment
rname	YOGAWORKS          *
sdate	10/05/2007
edate	10/08/2007
title	                                                                           
subtitle	                                                                           
glnum	71012  
phone	                               
website	                                        
email	                                        
desc	-
.
linked	
=cut
my @fields = qw/
    id
    name
    title
    subtitle
    glnum
    sdate
    edate
    url
    webdesc
    linked
    phone
    email
    housecost_id
    lunches
    status
/;
my %lookup = qw/
    rname	name
    website	url
    desc	webdesc
/;

my $r_sql = "insert into rental ("
    . (join ",", @fields)
. ") values ("
    . (join ",", ("?") x @fields)
. ")";
my $r_sth = $dbh->prepare($r_sql) or die "no prep rental insert\n";

my %hash;

for my $seas (@seasons) {
    print "rental $seas\n";
    open my $in, "<", "new/${seas}rent.txt"
        or die "no ${seas}rent: $!\n";
    %hash = ();
    while (<$in>) {
        s{\r?\n$}{};
        my ($k, $v) = split m{\t};
        $v =~ s{^\s*|\s*$}{}g;
        if ($v eq '-') {
            $v = "";
            LINE:
            while (<$in>) {
                s{\r?\n$}{};
                s{^\s*|\s*$}{}g;
                last LINE if m{^\.$};
                $v .= "$_\n";
            }
        }
        $k = $lookup{$k} || $k;
        $hash{$k} = $v;
        if ($k eq 'linked' && $hash{sdate}) {
            processRental($seas);
            %hash = ();
        }
    }
    close $in;
}
$r_sth = undef;
$dbh->disconnect();

sub processRental {
    my ($season) = @_;

    for my $f (qw/ sdate edate /) {
        $hash{$f} =~ s{(..)/(..)/(....)}{$3$1$2}g;
        $hash{$f} =~ s{[/\s]}{}g;
    }
    my $ndays = date($hash{edate}) - date($hash{sdate}) + 1;
    $hash{lunches} = '0' x $ndays;
    $hash{id} = undef;
    if ($hash{name} =~ s{\s*\*\s*$}{}) {
        $hash{ceu} = 'yes';
    }
    #print "rental $season - $hash{name}\n";
    $hash{housecost_id} = 1;        # Default
    $hash{status} = "new";
    $r_sth->execute(@hash{@fields});
}
