#!/bin/sh
if [ `whoami` = 'sahadev' ]
then
    db='mysql -u sahadev -pJonB reg2'
    export DBI_DSN="dbi:mysql:reg2"
    perl -p -i -e 's/autoincrement/auto_increment/' mk*
else
    db='sqlite3 retreatcenter.db'
    export DBI_DSN="dbi:SQLite:retreatcenter.db"
fi

echo creating tables
$db <mkpeople
$db <mkmisc
$db <mkprog
$db <mkrent
$db <mkrep
$db <mkusers
$db <mkmember
$db <mkreg
$db <mkevent
$db <mkacct
$db <mkmeet

echo strings
loadstr
echo affils
loadaf

echo clearing images
cd ../root/static/images
rm -f lo* lth* lb* po* pth* pb*
cd ../../../migration

echo people
loadpeople
echo leaders, canpol, housecost, programs
loadprog f89
echo registrations
loadreg f89
echo rentals
loadrent f89

# update the reg_count field in all program records
regcount

if [ `whoami` = 'jonbjornstad' ]
then
    cp retreatcenter.db ..
fi
