#!/bin/sh
echo You shouldn't be doing this!
exit
if [ `whoami` = 'sahadev' ]
then
    db='mysql -u sahadev -pJonB reg2'
    export DBI_DSN="dbi:mysql:reg2"
    perl -p -i -e 's/autoincrement/auto_increment/' mk*
    MYSQL=1
else
    db='sqlite3 ../retreatcenter.db'
    export DBI_DSN="dbi:SQLite:../retreatcenter.db"
    MYSQL=
fi

echo creating tables
echo acct   ; $db <mkacct
echo block  ; $db <mkblock
echo event  ; $db <mkevent
echo house  ; $db <mkhouse
echo meet   ; $db <mkmeet
echo member ; $db <mkmember
echo misc   ; $db <mkmisc
echo people ; $db <mkpeople
echo prog   ; $db <mkprog
echo reg    ; $db <mkreg
echo rent   ; $db <mkrent
echo rep    ; $db <mkrep
echo ride   ; $db <mkride
echo users  ; $db <mkusers
echo book   ; $db <mkbook

echo strings; $db <ldstr

loadaf

echo clearing images
cd ../root/static/images
rm -f 20*.png lo* lth* lb* po* pth* pb*
cd ../../../migration

echo people
loadpeople $MYSQL

echo leaders, canpol, housecost, programs
loadpr

# add a LOT of config records
loadconfig $MYSQL

loadbook
