#!/usr/bin/perl
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";

my $sql = "insert into event values (?,?,?,?,?,?,?)";
my $sth = $dbh->prepare($sql) or die "oops2 iss\n";
open my $evs, "<", "event/event.txt" or die "event/event.txt\n";
while (<$evs>) {
    chomp;
    while (m{\cM$}) {
        $_ .= <$evs>;
        chomp;
    }
    my @flds = split /\|/, $_, -1;
    for my $f (@flds) {
        $f = "" unless defined $f;
    }
    $sth->execute(@flds);
}
close $evs;

$sql = "insert into booking values (?, ?,?,?,?,?,?,?)";
$sth = $dbh->prepare($sql) or die "oops2 iss\n";
open my $bks, "<", "event/meet.txt" or die "event/meet.txt\n";
while (<$bks>) {
    chomp;
    while (m{\cM$}) {
        $_ .= <$bks>;
        chomp;
    }
    my @flds = split /\|/, $_, -1;
    for my $f (@flds) {
        $f = "" unless defined $f;
    }
    if (@flds == 6) {
        push @flds, '';
    }
    $sth->execute(undef, @flds);
}
close $bks;
$sth = undef;
$dbh->disconnect();
