#!/usr/bin/perl
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";

my $sth = $dbh->prepare("
    select p.first, p.last, m.amount, pr.name, m.the_date
    from mmi_payment m, people p, registration r, program pr
    where m.the_date > 20100101
      and m.person_id = p.id
      and m.reg_id = r.id
      and r.program_id = pr.id
      and m.amount != 0
      order by m.the_date
");
$sth->execute();
while (my ($first, $last, $amount, $program, $date) = $sth->fetchrow_array()) {
    $date =~ s{^....(..)(..)$}{$1/$2}msx;
    print "$date, $first, $last, $amount, $program\n";
}
