#!/usr/bin/perl
use strict;
use warnings;

use DBI;

my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "oh no\n";
my $sth = $dbh->prepare("
    select first, last, email, password, bg, fg, link
      from user
     where username = ?
");

mkdir "users" unless -d "users";
open my $out, ">", "users/users.txt"
    or die "cannot create users.txt: $!\n";

# save these users' password and display colors
# for later restoral during a loadall.
my @users = qw/
    sahadev
    jamal
    brajesh
    adrienne
    barnaby
    sukhdev
    tecla
    laura
    brajesh
    shyama
    rosemary
    richard
    lori
    pratibha
    soma
    jayanti
    thecla
    sunanda
    rebecca
    felicia
    nora
/;

for my $u (@users) {
    $sth->execute($u);
    my ($first, $last, $email, $password, $bg, $fg, $link)
        = $sth->fetchrow_array();
    for my $f ($first, $last, $email, $password, $bg, $fg, $link) {
        $f ||= "";
    }
    print {$out} join('|', $u, $first, $last, $email,
                               $password, $bg, $fg, $link), "\n";
}
