#!/usr/bin/perl
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect("dbi:SQLite:../retreatcenter.db", "sahadev", "JonB")
    or die "oh no\n";

mkdir "mem" unless -d "mem";
my @flds = ();

for my $tbl (qw/ member spons_hist night_hist /) {
    my $sql = "select * from $tbl";
    my $sth = $dbh->prepare($sql) or die "oops\n";
    $sth->execute();
    open my $mem, ">", "mem/$tbl.txt" or die "$tbl.txt\n";
    while (@flds = $sth->fetchrow_array()) {
        for my $f (@flds) {
            $f = "" unless defined $f;
        }
        print {$mem} join('|', @flds), "\n";
    }
    close $mem;
}
my $sql = "select p.id, p.last, p.first from people p, member m where m.person_id = p.id";
my $sth = $dbh->prepare($sql);
$sth->execute();
open my $mem, ">", "mem/people.txt" or die "people.txt\n";
while (@flds = $sth->fetchrow_array()) {
    for my $f (@flds) {
        $f = "" unless defined $f;
    }
    print {$mem} join('|', @flds), "\n";
}
close $mem;
undef $sth;
$dbh->disconnect();
