#!/bin/sh
who=`whoami`
if [ $who = 'sahadev' ]
then
    export DBI_DSN="dbi:mysql:reg2"
else
    export DBI_DSN="dbi:SQLite:../retreatcenter.db"
fi
savedon
savemem
saveiss
saveusers
saverent
saveprog
saveevent
tar cf backup.tar don mem iss users rent prog.txt meet event
if [ $who = 'sahadev' ]
then
    sendbackup
fi
