#!/bin/sh
if [ `whoami` = 'sahadev' ]
then
    cd /home/sahadev/Reg
    export DBI_DSN="dbi:mysql:reg2"
else
    cd /Users/jonbjornstad/Reg
    export DBI_DSN="dbi:SQLite:retreatcenter.db"
fi
script/add_config $* >>output/add_config 2>&1  &
