requires 'Devel::CheckLib';
requires 'Catalyst','5.90118';
requires 'Catalyst::Plugin::Static::Simple', '0.36';
requires 'Catalyst::Plugin::ServeFile', '0.004';
requires 'Catalyst::Plugin::Session::Store::DBIC';
requires 'DBD::mysql';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'Daemon::Control';
requires 'Email::Sender';
requires 'FCGI';
requires 'FCGI::ProcManager';
requires 'GD';
requires 'Image::Size';
requires 'JSON';
requires 'Mail::Sender';
requires 'MooseX::NonMoose';
requires 'Task::Catalyst::Tutorial';
requires 'Template', '2.27';
requires 'Spreadsheet::ParseExcel';
requires 'Spreadsheet::WriteExcel';
requires 'YAML';
