#!/bin/sh
cd /home/sahadev/Reg
day=`date +%d`
f=backup/rc.$day
rm -f $f $f.gz
mysqldump --user=root --add-drop-table --databases reg2 >$f
gzip $f
scp $f.gz sahadev@cloudkali:backup
test -f $HOME/sahadev/Reg/INACTIVE || scp $f.gz newkali:Reg/backup
