#!/bin/sh
day=`date +%d`
f=/var/Reg/backup/rc.$day
rm -f $f $f.gz
mysqldump --no-defaults --user=sahadev --password=JonB --add-drop-table \
    reg2 >$f 2>/dev/null
gzip $f
/usr/local/bin/s3cmd put $f.gz s3://backups-reg/sql/rc.$day.gz >>/var/log/Reg/s3cmd.log 2>&1
