#!/bin/sh
rst=/home/sahadev/Reg/root/static
for d in               \
    online online_done \
    mlist mlist_done   \
    req_mmi            \
    rides rides_done   \
    temple temple_done \
    templates
do
    rsync -avz --delete-after $rst/$d/ newkali:$rst/$d
done
