#!/bin/sh

if [ -d /home/sahadev/RetreatCenter ]; then

    cd /home/sahadev/RetreatCenter
    export DBI_DSN="dbi:mysql:reg2"

else 

    cd /Users/jonbjornstad/newReg/RetreatCenter
    export DBI_DSN="dbi:SQLite:$HOME/newReg/RetreatCenter/retreatcenter.db"

fi

if [ "$1" == "wait" ]; then
    script/grab_new >grab.out 2>&1
else
    script/grab_new >grab.out 2>&1 &
fi
