#!/bin/sh

cd /home/sahadev/RetreatCenter
export DBI_DSN="dbi:mysql:reg2"

# or

#cd /Users/jonbjornstad/newReg/RetreatCenter
#export DBI_DSN="dbi:SQLite:$HOME/newReg/RetreatCenter/retreatcenter.db"

script/grab_new >grab.out 2>&1 &
