#!/bin/sh
#exit
if [ -d /home/sahadev/Reg ]; then

    cd /home/sahadev/Reg
    export DBI_DSN="dbi:mysql:reg2"

else 

    cd /Users/jonbjornstad/Reg
    export DBI_DSN="dbi:SQLite:$HOME/Reg/retreatcenter.db"

fi

if [ "$1" == "wait" ]; then
    script/grab_new >>output/grab.out 2>&1
else
    script/grab_new  >>output/grab.out 2>&1 &
fi
