#!/bin/sh
r=/var/Reg
day=`date +%a`
f=$r/backup/grid.$day
rm -f $f $f.gz
cd $r/grid
tar cvf $f *data.txt >/var/Reg/output/grid.out 2>&1
gzip $f

cd ../rental_images
tar cvf $r/backup/rental_images.tar r-* rth-* >>/var/Reg/output/grid.out 2>&1

# and activity files
cd ../grab_new
tar cvf $r/backup/activity_files.tar * >>/var/Reg/output/grid.out 2>&1
