#!/usr/bin/env perl
use strict;
use warnings;

use Net::FTP;
use Mail::Sender;
use URI::Escape 'uri_escape';

my ($fname, $report_name, $who, $email) = @ARGV;
$report_name = uri_escape($report_name);

my $cgi = "https://www.mountmadonna.org/cgi-bin";
my $exp = "expiry_date.txt";
my $local_exp = "/var/Reg/report/$exp";

# hardcode for now...
my %string = qw(
    ftp_site mountmadonna.org
    ftp_login reg
    ftp_password S1tarAm!
    ftp_passive 1

    smtp_auth LOGIN
    smtp_pass BOI6Wu1bneKSiVbpVZv+iGIQpGxzlVifnW52rodluMMk
    smtp_port 25
    smtp_server email-smtp.us-west-2.amazonaws.com
    smtp_user AKIA455XE3II62QJTHXC
);

# 
# get ready to send email - dup'ed from script/grab_new
# someday we can make a shared sub...
#
sub email_letter {
    my (%args) = @_;

    my @auth = ();
    if ($string{smtp_auth}) {
        @auth = (
            auth    => $string{smtp_auth},
            authid  => $string{smtp_user},
            authpwd => $string{smtp_pass},
        );
    }
    my $mail_sender = Mail::Sender->new({
        smtp => $string{smtp_server},
        port => $string{smtp_port},
        @auth,
    }) or die("no mail sender");
    $args{to} =~ s{mountmadonna.org}{mountmadonnainstitute.org}; 
    $args{cc} =~ s{mountmadonna.org}{mountmadonnainstitute.org} if $args{cc}; 
    my @cc;
    if ($args{cc}) {
        push @cc, cc => $args{cc};
    }
    $mail_sender->Open({
        to       => $args{to},
        from     => $args{from},
        @cc,
        subject  => $args{subject},
        ctype    => "text/html",
        encoding => "7bit",
    }) or die("no mail sender Open");
    $mail_sender->SendLineEnc($args{html});
    $mail_sender->Close() or die("no mail sender Close");
}

sub finish {
    my ($status) = @_;
    print "DDUP status: $status\n";
    #email_letter(
    #   to      => $email, 
    #   from    => 'Mount Madonna Center <reservations@mountmadonna.org>',
    #   subject => "Your recent upload",
    #   html    => "The status of your recent upload was:<ul>$status",
#
#    );
    exit;
}

# thanks to jnap and haarg
# a nice HACK to force Extended Passive Mode:
local *Net::FTP::pasv = \&Net::FTP::epsv;
my $ftp = Net::FTP->new($string{ftp_site},
                        Passive => $string{ftp_passive})
    or finish("no Net::FTP->new");
$ftp->login($string{ftp_login}, $string{ftp_password})
    or finish("no login");
$ftp->cwd('update_dir')
    or finish("no cd");
$ftp->ascii()
    or finish("no ascii");
$ftp->put("/tmp/$fname", $fname)
    or finish("no put 1");
$ftp->put($local_exp, $exp)
    or finish("no put 2");
$ftp->quit();
my $rc = qx(curl -k '$cgi/load_people_data?report_name=$report_name&who=$who' 2>/dev/null);
if ($rc ne "done") {
    finish("no load");
}
finish("Success");
