#!/bin/bash
export DBI_DSN="dbi:mysql:reg2"
export PERL5LIB=/var/www/cpan-lib/lib/perl5
PATH=/var/www/cpan-lib/bin:/var/www/perl5.26.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
cd /var/www/src
/var/www/src/script/push_mem  >>/var/Reg/output/push_mem 2>&1
