#!/usr/bin/perl
# for some reason this doesn't work when invoked
# within Programs.pm sub export.
use strict;
use warnings;
use Net::FTP;

# MMC
my $ftp = Net::FTP->new("www.mountmadonna.org", Debug => 0, Passive => 0)
    or die "Cannot connect: $@";
$ftp->login("reg","S1tarAm!")
    or die "Cannot login ", $ftp->message;
$ftp->binary();
$ftp->put('exported_reg_data.tgz');
$ftp->quit();

# MMI
$ftp = Net::FTP->new("www.mountmadonnainstitute.org", Debug => 0, Passive => 0)
    or die "Cannot connect: $@";
$ftp->login("reg","S1tarAm!")
    or die "Cannot login ", $ftp->message;
$ftp->binary();
$ftp->put('exported_reg_data.tgz');
$ftp->quit();

use LWP::Simple qw(get);
print get('https://reg:S1tarAm!@www.mountmadonna.org/feeds_from_reg/go.php');
print get('https://reg:S1tarAm!@www.mountmadonnainstitute.org/feeds_from_reg/go.php');
