#!/usr/bin/perl
# for some reason this doesn't work when invoked
# within Programs.pm sub export.
use strict;
use warnings;
use Net::FTP;

# MMC
my $ftp = Net::FTP->new("52.53.150.121", Debug => 0)
    or die "Cannot connect: $@";
$ftp->login("reg","S1tarAm!")
    or die "Cannot login ", $ftp->message;
$ftp->binary();
$ftp->put('exported_reg_data.tgz');
$ftp->quit();

# MMI
$ftp = Net::FTP->new("54.67.32.96", Debug => 0)
    or die "Cannot connect: $@";
$ftp->login("reg","S1tarAm!")
    or die "Cannot login ", $ftp->message;
$ftp->binary();
$ftp->put('exported_reg_data.tgz');
$ftp->quit();

use LWP::Simple qw(get);
print get('https://reg:S1tarAm!@mmc.cosmicdev.com/mmc-dev-team/feeds_from_reg/go.php');
print get('https://reg:S1tarAm!@mmi.cosmicdev.com/mmi-dev-team/feeds_from_reg/go.php');
