#!/bin/bash
REGDIR=/Users/jonbjornstad/Reg
DIRFTP=$REGDIR/file_ftp_dir
TEST_EMAIL=jon@sucenter.org

# clear the field - including the people records that we will be creating
clear_field.pl

# online MMI registrations and donations (two kinds of transactions)
# a personal retreat and a temple donation
# the temple donation may be done differently by Shantam
cp from_kali/online/{7341853503,7316527613} $DIRFTP/www/cgi-bin/transactions

# mlist requests from mmc and mmi
cp from_kali/mlist/* $DIRFTP/www/cgi-bin/mlist_requests

# functional test - poke some Rental with the code SITLZO
# grid
cp from_kali/grid/SITLZO-data.txt $DIRFTP/www/cgi-bin/rental/ftp_dir

# ride requests
cp from_kali/rides/* $DIRFTP/www/cgi-bin/ride_requests

# online member payments
cp from_kali/omp/* $DIRFTP/www/cgi-bin/omp_dir

# MMI registrations
cp from_kali/online/7353331213 $DIRFTP/domains/mountmadonnainstitute.org/public_html/cgi-bin/transactions

# MMI payment requests
# functional/manual test:
# 1 - add an MMI program
# 2 - register someone
# 3 - put them on automatic payment
# 4 - house them
# 5 - request multiple online payments
# 6.0 touch /tmp/testing_req_mmi
# 6.1 - send them (even if not online)
# 7.0 - move the /tmp/$code file to from_kali/req_mmi (as the only file there)
# 7.1 delete /tmp/testing_req_mmi
# 8 - run this test_grab_new
# 9 - verify that the requested payments became real payments.
#     and that the file $code appears in root/static/req_mmi/yyyy_mm
#
cp from_kali/req_mmi/* \
   $DIRFTP/domains/mountmadonnainstitute.org/public_html/cgi-bin/req_mmi_dir/paid

# temple registration
cp from_kali/temple/* $DIRFTP/www/temple/_updates/users

rm -f grab_running
FILE_FTP_DIR=$DIRFTP perl script/grab_new

# here are the tests:
check_field.pl
