#!/usr/bin/perl
use strict;
use warnings;

use CGI qw/:standard/;
use CGI::Carp qw/fatalsToBrowser/;
use DBI;
use lib 'mylib/lib/perl5';
use Date::Simple qw/today/;

print header();

my $dbh = DBI->connect(
    'dbi:SQLite:dbname=people_data', '', '',
    { RaiseError => 1, AutoCommit => 1 }
) or die "cannot connect to database\n";

my $sth = $dbh->prepare("select * from people_data where status = 1");
$sth->execute();
open my $out, '>', "updates.sql";
my $today = today()->as_d8();
while (my $p = $sth->fetchrow_hashref()) {
    my $sql = "update people set";
    FIELD:
    for my $f (sort keys %$p) {
        next FIELD if $f eq 'id' || $f eq 'secure_code' || $f eq 'status';
        $sql .= qq[ $f = "$p->{$f}",];
    }
    $sql .= qq[ date_updat = "$today"];
    $sql .= qq[ where secure_code = "$p->{secure_code}"];
    print {$out} "$sql;\n";
}
close $out;
$sth = $dbh->prepare("update people_data set status = 2 where status = 1");
$sth->execute();
print "gotten";
