#!/usr/bin/perl
use strict;
use warnings;

use CGI qw/:standard/;
use DBI;

my $dbh = DBI->connect(
    'dbi:SQLite:dbname=people_data', '', '',
    { RaiseError => 1, AutoCommit => 1 }
) or die "cannot connect to database\n";

my $sth = $dbh->prepare("select count(*) from people_data");
$sth->execute();
my ($all) = $sth->fetchrow_array();

my $sth = $dbh->prepare("select count(*) from people_data where status = 1");
$sth->execute();
my ($viewed) = $sth->fetchrow_array();

$sth = $dbh->prepare("select count(*) from people_data where status = 2");
$sth->execute();
my ($changed) = $sth->fetchrow_array();

$sth = $dbh->prepare("select count(*) from people_data where status = 3");
$sth->execute();
my ($total) = $sth->fetchrow_array();
# total people who have either viewed or changed and HAVE
# been imported.

$sth = $dbh->prepare("select count(*) from people_data where status = 4");
$sth->execute();
my ($expired) = $sth->fetchrow_array();

my $pct = int((100*$total/$all) + .5);
print header();
print "$expired <a href=http://www.mountmadonna.org/cgi-bin/get_expired_updates>expired</a>, " if $expired;
print "$viewed viewed, $changed changed - imported $total of $all = $pct%\n";
