#!/usr/bin/perl
use strict;
use warnings;

use CGI qw/:standard/;
use DBI;
use lib 'mylib/lib/perl5';
use Template;

my $dbh = DBI->connect(
    'dbi:SQLite:dbname=people_data', '', '',
    { RaiseError => 1, AutoCommit => 1 }
) or die "cannot connect to database\n";

my $sth = $dbh->prepare(
    "select count(*) from people_data where updated = 1");
$sth->execute();
my ($count) = $sth->fetchrow_array();
print header(), "$count\n";
