#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use Encode qw/
    encode_utf8
/;
use open ":std", ":encoding(UTF-8)";
use DB_File;
use Text::CSV;
my $csv = Text::CSV->new({ binary => 1, auto_diag => 1});

unlink 'vocab.dbm';
my %vocab;
tie %vocab, 'DB_File', 'vocab.dbm';

unlink 'alternates.dbm';
my %alternates;
tie %alternates, 'DB_File', 'alternates.dbm';

sub process {
    my ($file) = @_;
    open my $in, '<:encoding(utf8)', $file 
        or die "no $file";
    my $first_header_aref = $csv->getline($in);
    while (my $aref = $csv->getline($in)) {
        my $word = encode_utf8($aref->[3]);
        $vocab{$word} = $word;
        my @alt_words;
        for my $i (4 .. $#$aref) {
            if ($aref->[$i] =~ /\S/) {
                my $s = encode_utf8($aref->[$i]);
                $vocab{$s} = $word;
                push @alt_words, $s;
            }
        }
        if (@alt_words) {
            $alternates{$word} = join '||', @alt_words;
        }
    }
}

process('english.csv');
process('sanskrit.csv');
process('names.csv');
process('techniques.csv');
