#!/usr/local/bin/perl
use strict;
use warnings;
use lib 'lib';

use Date::Simple qw/
    today
/;

use DBH;
DBH->init();

my @classes;
for my $t (<lib/DB/*.pm>) {
    require $t or die "no require of $t";
    my $class = $t;
    $class =~ s{lib/DB/(\w+)[.]pm}{DB::$1}xms;
    push @classes, $class;
}
@classes = sort { $a->order() <=> $b->order() } @classes;
my $today = today();
CLASS:
for my $cl (@classes) {
    my $order = $cl->order();
    if ($order == 0) {
        next CLASS;
    }
    print "$order: $cl";
    $cl->create();
    $cl->init($today);
    print "\n";
}
