#!/usr/bin/env perl
use strict;
use warnings;

use lib "lib";
use RetreatCenterDB;
use Util qw/
    model
    db_init
/;
my $c = db_init();

use Date::Simple qw/
    today
    date
/;
my $today = today()->as_d8();

for my $p (
    model($c, 'Program')->search(
        { sdate => $today },
        { order_by => 'sdate' }
    )
) {
    print $p->name, ' => ', $p->sdate, "\n";
}
