#!/bin/sh
# am example of how to call this script:
#
# running as sahadev (a normal user)
# ./get_prod_data sahadev ec2-13-57-186-109.us-west-1.compute.amazonaws.com reg:www-data
#
USER=$1
HOST=$2
PERMISSIONS=$3

# grid data
ssh $USER@$HOST \
    "ls -1tr /var/reg_backup/grid.* | tail -1" \
    | xargs -iz -I '{}' \
    scp $USER@$HOST:{} .
tar zxvf grid.* -C /var/Reg/grid
chmod 664 /var/Reg/grid/*
sudo chown $PERMISSIONS /var/Reg/grid/*

# rental images
scp $USER@$HOST:/var/reg_backup/rental_images.tar .
tar xvf rental_images.tar -C /var/Reg/rental_images
chmod 664 /var/Reg/rental_images/*
sudo chown $PERMISSIONS /var/Reg/rental_images/*

# activity files
scp $USER@$HOST:/var/reg_backup/activity_files.tar .
tar xvf activity_files.tar -C /var/Reg/grab_new
chmod 664 /var/Reg/grab_new/*
sudo chown $PERMISSIONS /var/Reg/grab_new/*

# mysql data
ssh $USER@$HOST \
    "ls -1tr /var/reg_backup/rc.* | tail -1" \
    | xargs -iz -I '{}' \
    scp $USER@$HOST:{} .
pv rc.* | gunzip | mysql

rm rc.* grid.* rental_images.tar activity_files.tar

mysql <<EOS
-- new mechanism for session data
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
    id           CHAR(72) PRIMARY KEY,
    session_data TEXT,
    expires      INTEGER
);

-- all email comes to us
UPDATE string
   SET   value = 'jon@suecenter.org, jjn1056@gmail.com'
 WHERE the_key = 'redirect_email';

-- talk to the clone of mountmadonna.org
UPDATE string
   SET   value = 'mmc.jasongaluten.com'
 WHERE the_key = 'ftp_site';

-- separate script for this:
-- remove any reference to rides and drivers
DROP TABLE IF EXISTS ride;
DELETE FROM role where role = 'ride_admin';
DELETE FROM role where role = 'driver';
DELETE FROM user_role where role_id in (12, 13);

DELETE FROM string where the_key like '%ride%';
DELETE FROM string where the_key = 'max_shuttles' OR the_key = 'ftp_userpics';
DELETE FROM string where the_key like 'MRY%';
DELETE FROM string where the_key like 'OAK%';
DELETE FROM string where the_key like 'OTH%';
DELETE FROM string where the_key like 'SFO%';
DELETE FROM string where the_key like 'SJC%';
DELETE FROM string where the_key like '%imgwidth';

INSERT INTO string (the_key, value) VALUES ('curl_command', 'http://mmc.jasongaluten.com/feeds_from_reg/go.php');
INSERT INTO string (the_key, value) VALUES ('curl_mmi_command', 'http://mountmadonnainstitute.org/feeds_from_reg/go.php');

DROP TABLE IF EXISTS program_doc;

-- comment these out once the production db has dropped the columns
-- no images for leaders
ALTER TABLE leader DROP COLUMN image;
-- no images for programs
ALTER TABLE program DROP COLUMN image;
-- no images for residents
ALTER TABLE resident DROP COLUMN image;
-- no documents for programs

EOS
