#!/bin/sh
# am example of how to call this script:
#
# running as sahadev (a normal user)
# ./get_prod_data sahadev ec2-13-57-186-109.us-west-1.compute.amazonaws.com reg:www-data
#
USER=$1
HOST=$2
PERMISSIONS=$3

# do we need to do this?
# ssh-keyscan ec2-13-57-186-109.us-west-1.compute.amazonaws.com >>~/.ssh/known_hosts
# OR:
# ssh-keyscan $HOST >>~/.ssh/known_hosts
# and maybe do it only once?

# grid data
ssh $USER@$HOST \
    "ls -1tr /var/reg_backup/grid.* | tail -1" \
    | xargs -iz -I '{}' \
    scp $USER@$HOST:{} .
tar zxvf grid.* -C /var/Reg/grid
chmod 664 /var/Reg/grid/*
sudo chown $PERMISSIONS /var/Reg/grid/*

# rental images
scp $USER@$HOST:/var/reg_backup/rental_images.tar .
tar xvf rental_images.tar -C /var/Reg/rental_images
chmod 664 /var/Reg/rental_images/*
sudo chown $PERMISSIONS /var/Reg/rental_images/*

# activity files
scp $USER@$HOST:/var/reg_backup/activity_files.tar .
tar xvf activity_files.tar -C /var/Reg/grab_new
chmod 664 /var/Reg/grab_new/*
sudo chown $PERMISSIONS /var/Reg/grab_new/*

# mysql data
ssh $USER@$HOST \
    "ls -1tr /var/reg_backup/rc.* | tail -1" \
    | xargs -iz -I '{}' \
    scp $USER@$HOST:{} .
pv rc.* | gunzip | mysql

rm rc.* grid.* rental_images.tar activity_files.tar
