#!/usr/bin/env perl
use strict;
use warnings;
use lib 'lib';
use RetreatCenterDB;
use Util qw/
    model
    db_init
/;
my $date = shift;
sub quote {
    return '"' . $_[0] . '"';
}
my $c = db_init();
print "First, Last, Amount, Date, Address1, Address2, City, State, Zip\n";
          ($per->first, $per->last,
          $pay->amount, $pay->the_date_obj->format("%D"),
          $per->addr1,
          $per->addr2, $per->city, uc $per->st_prov,
          $per->zip_post);
for my $pay (model($c, 'XAccountPayment')->search(
             {
                 xaccount_id => 101,
                 the_date    => { '>=' => $date },
             },
             {
                order_by => [ 'the_date' ],
             }
)) {
    my $per = $pay->person();
    if (! $per) {
        next;
    }
    print join ',',
          map {
              quote($_);
          }
          ($per->first, $per->last,
          $pay->amount, $pay->the_date_obj->format("%D"),
          $per->addr1,
          $per->addr2, $per->city, uc $per->st_prov,
          $per->zip_post);
    print "\n";
}
