#!/usr/bin/perl
use strict;
use warnings;
use lib 'lib';
use RetreatCenterDB;
use Digest::MD5 qw(md5_hex);

my $schema = RetreatCenterDB->connect($ENV{DBI_DSN}, "sahadev", "JonB");

my @users = $schema->resultset('User')->search({
    password   => { -not_like => '%-no login-%' },
});
for my $user (@users) {
    $user->update({
      password => md5_hex($user->password),
    });
}
