#!/bin/bash
cd /var/Reg
mkdir -p backup export grab_new grid mlist_done \
    omp omp_done online online_done rental_deposit report \
    req_mmc req_mmi rides temple_donation words output \
    rides_done
chmod 775 *
chown reg:www-data *
