#!/bin/bash
mysql <<EOS
-- new mechanism for session data
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
    id           CHAR(72) PRIMARY KEY,
    session_data TEXT,
    expires      INTEGER
);

-- separate script for this:
-- remove any reference to rides and drivers
DROP TABLE IF EXISTS ride;
DELETE FROM role where role = 'ride_admin';
DELETE FROM role where role = 'driver';
DELETE FROM user_role where role_id in (12, 13);

DELETE FROM string where the_key like '%ride%';
DELETE FROM string where the_key = 'max_shuttles' OR the_key = 'ftp_userpics';
DELETE FROM string where the_key like 'MRY%';
DELETE FROM string where the_key like 'OAK%';
DELETE FROM string where the_key like 'OTH%';
DELETE FROM string where the_key like 'SFO%';
DELETE FROM string where the_key like 'SJC%';
DELETE FROM string where the_key like '%imgwidth';

UPDATE string set value = '1' where the_key = 'ftp_passive';

DROP TABLE IF EXISTS program_doc;

-- no images for leaders
ALTER TABLE leader DROP COLUMN image;
-- no images for programs
ALTER TABLE program DROP COLUMN image;
-- no images for residents
ALTER TABLE resident DROP COLUMN image;
-- no documents for programs

EOS
