#!/usr/bin/env perl

use strict;
use warnings;
use RetreatCenterDB;
use Util qw(db_init email_letter);

my $c = db_init();

foreach my $cnt (1..25) {
    email_letter($c,
        to      => 'jjn1056@gmail.com',
        from    => 'test-stuffer@mountmadonna.org',
        subject => "Hanuman Fellowship Membership Status (${\scalar(localtime)}) # $cnt",
        html    => 'Test Body ' x 1000, # Similate some longer emails
    );
}

