#!/bin/bash

# Ok, only run this on your development VM.  This is used to set your devVM
# database to have local dev only values (like  don't send emails for real).
# We also clear out the sessions table and etc to prevent snooping :)

mysql <<EOS
-- new mechanism for session data
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
    id           CHAR(72) PRIMARY KEY,
    session_data TEXT,
    expires      INTEGER
);

UPDATE string SET value = 'jonb@logicalpoetry.com, jjn1056@gmail.com, shank76@gmail.com' 
    WHERE the_key = 'redirect_email';

UPDATE string set value = 'https://mmc.jasongaluten.com'
    WHERE the_key = 'url_prefix';

UPDATE string set value = 'mmc.jasongaluten.com'
    WHERE the_key = 'ftp_site';
UPDATE string set value = 'https://mmc.jasongaluten.com/feeds_from_reg/go.php'
    WHERE the_key = 'curl_command';

UPDATE string set value = 'https://mmc.jasongaluten.com/cgi-bin/req_pay'
    WHERE the_key = 'prepay_link';
UPDATE string set value = 'https://mmc.jasongaluten.com/cgi-bin/grid'
    WHERE the_key = 'grid_url';
UPDATE string set value = 'https://mmc.jasongaluten.com/cgi-bin/rental_deposit'
    WHERE the_key = 'rental_deposit_url';
UPDATE string set value = 'https://mmc.jasongaluten.com/cgi-bin/omp_load'
    WHERE the_key = 'omp_load_url';
UPDATE string set value = 'https://mmc.jasongaluten.com/cgi-bin/omp_pay'
    WHERE the_key = 'omp_pay_url';

-- mmi
UPDATE string set value = 'mmi.jasongaluten.com'
    WHERE the_key = 'ftp_mmi_site';
UPDATE string set value = 'https://mmi.jasongaluten.com/feeds_from_reg/go.php'
    WHERE the_key = 'curl_mmi_command';

UPDATE string set value = 'mmc.jasongaluten.com AND mmi.jasongaluten.com'
    WHERE the_key = 'ftp_export_site';
EOS
