#!/usr/bin/env perl
use warnings;
use strict;
use CGI;
my $q = CGI->new();
print $q->header();
use lib '.', '../lib';
use Util qw/
    db_init
    model
/;
my $c = db_init();
use Date::Simple qw/
    date
/;
use Time::Simple qw/
    get_time
/;
my $code = $q->param('code');
my @cards = model($c, 'GiftCards')->search({
                code => $code,
            },
            {
                order_by => qw/ the_date the_time /,
            });
my $header = 0;
my $balance = 0;
for my $card (@cards) {
    if (! $header) {
        print <<'EOH';
<html>
<head>
<link rel="stylesheet" href="/static/cgi.css">
</head>
<body>
<img src='/static/images/mmc-teal.png' width=200>
EOH
        print "<h2>Status of MMC Gift Card with code '$code'</h2>\n";
        print "<table cellpadding=5>\n";
        $header = 1;
    }
    print "<tr><td>"
        . $card->the_date_obj->format("%D")
        . "</td><td>"
        . $card->the_time_obj->ampm()
        . "</td>"
        . "<td align=right>"
        . '$' . $card->amount
        . "</td><td>"
        ;
    $balance += $card->amount;
    if ($card->rec_lname) {
        my $person = $card->person;
        print "Purchased by "
            . $person->name
            . " for "
            . $card->rec_fname . ' ' . $card->rec_lname
            . "</td>"
            ;
    }
    else {
        my $s = $card->rec_fname;
        $s =~ s{<a[^>]*>}{}xmsg;
        $s =~ s{</a>}{}xmsg;
        print "$s</td>";
    }
    print "</tr>\n";
}
if (! $header) {
    print "Sorry, no gift card was found with the code '$code'";
}
else {
    print "<tr><td colspan=2 align=right>Balance</td><td align=right>\$$balance</td></tr>\n";
    print "</table>\n";
}
print <<'EOH';
</body>
</html>
EOH
