#!/usr/bin/env perl
use strict;
use warnings;
use Template;
use CGI;
my $q = CGI->new();
print $q->header();
use CGI::Carp qw/fatalsToBrowser/;

use lib '.', '../lib';
use Util qw/
    db_init
    model
/;
my $c = db_init();
use Date::Simple qw/
    date
/;
use HousingNames qw/
    %housing_name
/;

my %cookie = $q->cookie(-name => 'user_data');
my %stash;

for my $w (qw/
    rec_fname rec_lname rec_email
    fname lname street1 street2
    city state zip country
    cell
    email1
/) {
    $stash{$w} = $cookie{$w} || "";
}
$stash{email2} = $cookie{email1} || "";

Template->new({
    INCLUDE_PATH => '.',
    INTERPOLATE => 1,
})->process(
    'gift_card1.tt2',
    \%stash,
) or die "no template\n";
