#!/usr/bin/env perl
use strict;
use warnings;
use CGI;
my $q = CGI->new();
use CGI::Carp qw/fatalsToBrowser/;
use lib '.', '../lib';
use Template;
use Stripe qw/
    stripe_payment
/;

#
# gather all the form elements into a hash
#
my %form = $q->Vars();
for my $w (keys %form) {
    $form{$w} =~ s{^\s*|\s*$}{}g;       # trim the fields
}
# form defaults
#
if ($form{country} !~ /\S/) {
    $form{country} = "USA";     # default
}

my %cookie = %form;
my $cookie = $q->cookie(
    -name    => 'user_data',
    -value   => \%cookie,
    -expires => '+10y',     # i.e. don't expire
    -domain  => 'www.mountmadonna.org',
);
print $q->header(-cookie => $cookie);

#
# prepare the confirmation page.
#

my $amount = $form{amount}; 

my %stash;
for my $name (qw/
    rec_first rec_last rec_email
    first last addr1 addr2 city st_prov zip_post
    country cell email1 personal_note
/) {
    $stash{$name} = $form{$name};
}
if ($form{personal_note}) {
    my $s = $form{personal_note};
    $s =~ s{\n}{<br>}xmsg;
    $stash{personal_note_verbose} = $s;
}

#
# create a readable description for the user
#
$stash{cell} = $form{cell};

#
# in addition to the addr1, addr2 above
# which are for the hidden fields we also have
#
my $street_addr = $form{street1};
if ($form{street2} =~ /\S/) {
    $street_addr .= "<br>$form{street2}";
}
$stash{street_addr} = $street_addr;

my %metadata = qw/
    amount => $amount,    
/;

my $stripe = stripe_payment(
    name        => 'Gift Card',
    description => "Gift Card for $form{rec_first} $form{rec_last}",
    amount      => $total,
    metadata    => \%metadata,
    email       => $form{email1},
);
if ($stripe !~ /Pay Securely/) {
    oops($stripe, 1);
}
$stash{stripe_payment} = $stripe;

Template->new(
    INTERPOLATE => 1,
)->process(
    'gift_card2.tt2',
    \%stash,
);
