#!/usr/bin/env perl
use strict;
use warnings;
use Template;
use CGI;
my $q = CGI->new();
print $q->header();
use CGI::Carp qw/fatalsToBrowser/;

use lib '.', '../lib';
use Util qw/
    db_init
    model
/;
my $c = db_init();
use Date::Simple qw/
    date
    today
    days_in_month
/;
my $today = today();
my $y = $today->year;
my $m = $today->month;
my $dm = days_in_month($y, $m);
my $first = date($y, $m, 1)->as_d8();
my $last  = date($y, $m, $dm)->as_d8();
my %stash;
my ($pr) = model($c, 'Program')->search({
               name => { -like => '%personal%retreat%' },
               sdate => { -between => [ $first, $last ] },
           });
my $hc = $pr->housecost();
my @htypes = model($c, 'HousingType')->all();
my @fee_rows = sort {
                   $a->{order} <=> $b->{order}
               }
               map { 
                   my $type = $_->name;
                   +{
                        type      => $type,
                        short_desc => $_->short_desc,
                        cost       => $hc->$type,
                        order      => $_->ht_order,
                    }
               }
               grep {
                  my $type = $_->name;
                  $hc->$type != 0
               }
               @htypes;

$stash{housecost_type} = $hc->type;
$stash{htypes} = \@fee_rows;

my %cookie = $q->cookie(-name => 'user_data');
$stash{month} = $today->format("%B");
$stash{fee_rows} = \@fee_rows;

for my $w (qw/
    rec_fname rec_lname rec_email
    first last addr1 addr2
    city st_prov zip_post country
    cell
    email1
/) {
    $stash{$w} = $cookie{$w} || "";
}
$stash{email2} = $cookie{email1} || "";

Template->new({
    INTERPOLATE => 1,
})->process(
    'gift_card1.tt2',
    \%stash,
) or die "no template\n";
