#!/usr/bin/env perl
use strict;
use warnings;
use lib '.', '../lib';
use Util qw/
    db_init
    model
    fee_types
    styled
    check_read_only
/;
check_read_only();

use Template;
use CGI;
my $q = CGI->new();
print $q->header();
use CGI::Carp qw/fatalsToBrowser/;

my $c = db_init();
use Date::Simple qw/
    date
    today
    days_in_month
/;
my $today = today();
my $y = $today->year;
my $m = $today->month;
my $dm = days_in_month($y, $m);
my $first = date($y, $m, 1)->as_d8();
my $last  = date($y, $m, $dm)->as_d8();
my %stash;
my ($pr) = model($c, 'Program')->search({
               name => { -like => '%personal%retreat%' },
               sdate => { -between => [ $first, $last ] },
           });

my $hc = $pr->housecost();
$stash{housecost_type} = $hc->type;
$stash{htypes} = fee_types($c, $hc);

my %cookie = $q->cookie(-name => 'user_data');
$stash{month} = $today->format("%B");

for my $w (qw/
    rec_fname rec_lname rec_email
    first last addr1 addr2
    city st_prov zip_post country
    cell
    email1
/) {
    $stash{$w} = $cookie{$w} || "";
}
$stash{email2} = $cookie{email1} || "";

Template->new({
    INTERPOLATE => 1,
})->process(
    styled('gift_card1.tt2'),
    \%stash,
) or die "no template\n";
