#!/usr/bin/env perl
use strict;
use warnings;
use CGI;
my $q = CGI->new();
use CGI::Carp qw/fatalsToBrowser/;
use lib '.', '../lib';
use Template;
use Stripe qw/
    stripe_payment
/;

#
# gather all the form elements into a hash
#
my %form = $q->Vars();
for my $w (keys %form) {
    $form{$w} =~ s{^\s*|\s*$}{}g;       # trim the fields
}
# form defaults
#
if ($form{country} !~ /\S/) {
    $form{country} = "USA";     # default
}

my %cookie = %form;
my $cookie = $q->cookie(
    -name    => 'user_data',
    -value   => \%cookie,
    -expires => '+10y',     # i.e. don't expire
    -domain  => '.mountmadonna.org',
);
print $q->header(-cookie => $cookie);

#
# prepare the confirmation page.
#

my $amount = $form{amount}; 

my (%stash, %metadata);
for my $name (qw/
    rec_fname rec_lname rec_email
    first last addr1 addr2 city st_prov zip_post
    country cell personal_note
    amount
/) {
    $stash{$name} = $form{$name};
}
# rename...
$stash{email} = $form{email1};

if ($form{personal_note}) {
    my $s = $form{personal_note};
    $s =~ s{\n}{<br>}xmsg;
    $stash{personal_note_verbose} = $s;
}

#
# create a readable description for the user
#
#
# in addition to the addr1, addr2 above
# we have street_addr
#
my $street_addr = $form{addr1};
if ($form{street2} =~ /\S/) {
    $street_addr .= "<br>$form{addr2}";
}
$stash{street_addr} = $street_addr;

$stash{stripe_payment} = stripe_payment(
    name        => 'Gift Card',
    description => "Gift Card for \u$form{rec_fname} \u$form{rec_lname}",
    amount      => $amount,
    metadata    => \%stash,
    email       => $form{email1},
);

Template->new(
    INTERPOLATE => 1,
)->process(
    'gift_card2.tt2',
    \%stash,
);
