#!/usr/bin/env perl
use strict;
use warnings;
use DBI;
my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "cannot connect to database\n";
my $ins_sth = $dbh->prepare(<<'EOS');
    INSERT
      INTO sutra
           (id, content)
    VALUES (?, ?)
EOS
chdir 'sutras';
for my $id (<[0-9]*>) {
    open my $in, '<', $id;
    my $s;
    {
        local $/;
        $s = <$in>;
    }
    $id =~ s{\A 0*}{}xms;
    $ins_sth->execute($id, $s);
}
