#!/usr/bin/env perl
use strict;
use warnings;
use lib '../lib';
use Util qw/
    styled
/;
print "Content-Type: text/html; charset=ISO-8859-1\n\n";
open my $in, '<', styled('meals_at_mmc.html');
print <$in>;
