#!/usr/bin/env perl
use strict;
use warnings;

use lib '.', '../lib';

use CGI;
my $q = CGI->new();
print $q->header();

use Util qw/
    add_or_update_deduping
    add_membership_payment
    member_notify
    db_init
/;
my $c = db_init();

use Stripe qw/
    metadata
/;
my %P = metadata($q);

#
# create/update the Person
#
# first add missing keys - we're not a full mlist thingy
#
$P{sex} = '';
for my $k (qw/ e_mailings snail_mailings share_mailings /) {
    $P{$k} = '';    # default to no for new people?
}
$P{tel_cell} = $P{cell};
for my $f (qw/
    temple_id
    tel_home tel_work
/) {
    $P{$f} = '';
}
my ($person_id, $person, $status) = add_or_update_deduping(
                                        $c, \%P
                                    );
my $member_id = 0;
if (my $mem = $person->member) {
    # unlikely - unless ... wanting to change
    # from General to Sponsor...
    $member_id = $mem->id;
}

#
# create the Membership and add the payment
#
add_membership_payment($c, $member_id, $person_id,
                       $P{amount}, 'O', $P{transaction_id});

member_notify($c, $person, $P{mem_type},
              $P{amount}, $P{transaction_id},
              {
                  intro => $P{intro},
                  ky    => $P{ky},
                  pic   => $P{pic},
              }
             );
