#!/usr/bin/env perl
use strict;
use warnings;
use CGI;
my $q = CGI->new();
print $q->header();
use lib '.', '../lib';
use Stripe qw/
    metadata
/;
use Util qw/
    db_init
    model
    add_membership_payment
    member_notify
/;
my $c = db_init();
use Template;

my %P = metadata($q);

my $member = model($c, 'Member')->find($P{member_id});
add_membership_payment($c, $P{member_id}, 0,
                       $P{amount}, 'O', $P{transaction_id});

member_notify($c, $member->person, $P{category},
              0, $P{amount}, $P{transaction_id});
