#!/usr/bin/env perl
use strict;
use warnings;
use CGI;
my $q = CGI->new();
print $q->header();
use lib '.', '../lib';
use Stripe qw/
    metadata
/;
use Template;
use Util qw/
    JON
/;
use Data::Dumper;
$Data::Dumper::Sortkeys = 1;

my %P = metadata($q);
my $d = Dumper(\%P);

# Two regs at once???
open my $out, '>', '/var/Reg/online/N' . time();
                            # N for new format
print {$out} $d;
close $out;

Template->new(
    INTERPOLATE => 1
)->process(
    'message.tt2',
    \%P,
);
