#!/usr/bin/env perl
use strict;
use warnings;
print "Content-Type: text/html; charset=ISO-8859-1\n\n";
use Template;
use lib '../lib';
use Date::Simple qw/
    today
/;

use Util qw/
    db_init
    model
    styled
/;
my $c = db_init();
my (@events) = model($c, 'Event')->search(
    {
        name  => { 'regexp' => '[[:<:]]No[[:>:]].*[[:<:]]PRs?[[:>:]]' },
        edate => { '>='   => today()->as_d8() },
    },
    {
        order_by => 'sdate',
    }
);
my @disabled;
my (@noPR, @noPRindoors);
for my $ev (@events) {
    my ($sdate, $edate) = ($ev->sdate_obj, $ev->edate_obj);
    my ($indoors)       = $ev->name =~ m{indoors}xmsi;
    my $s;
    if ($sdate->month() == $edate->month()) {
        if ($sdate->day() == $edate->day()) {
            $s = $sdate->format("%B %e '%q");
        }
        else {
            $s = $sdate->format("%B %e")
               . "-"
               . $edate->format("%e '%q")
               ;
        }
    }
    else {
        $s = $sdate->format("%B %e '%q")
             .  " - "
             . $edate->format("%B %e '%q")
             ;
    }
    if ($indoors) {
        push @noPRindoors, $s;
    }
    else {
        push @noPR, $s;
        for (my $d = $sdate; $d <= $edate; ++$d) {
            push @disabled, $d->format("%m/%d/%Y");
        }
    }
}
my %stash;
$stash{noPR} = \@noPR;
$stash{noPRindoors} = \@noPRindoors;
my $today = today();
my $start = $today + 2;
my $end = $today + 90;
$stash{startDate} = $start->format("%m/%d/%Y");
$stash{endDate} = $end->format("%m/%d/%Y");
$stash{disabled} = join ', ', map { qq!'$_'! } @disabled;

Template->new(
    INTERPOLATE => 1,
)->process(
    styled('regpr.tt2'),
    \%stash,
);
