#!/usr/bin/env perl
use strict;
use warnings;

use CGI;
my $q = CGI->new();
print $q->header();
use CGI::Carp qw/fatalsToBrowser/;
use Template;
use lib '.', '../lib';
use Stripe qw/
    stripe_payment
/;
use Util qw/
    commify
/;
my $code = $q->param('code');
if (! -f "/var/Reg/req_mmc_sent/$code") {
    # this file was put there when the
    # request was sent to the person
    print "Something is wrong with $code.\n";
    exit;
}
my $href = do "/var/Reg/req_mmc_sent/$code";
my %data = %$href;

my %stash = (
    payment_for => "Payment for MMC Program '$data{program}'",
    amount   => $data{total},
    first    => $data{first},
    last     => $data{last},
    addr     => $data{addr},
    city     => $data{city},
    state    => $data{st_prov},
    zip      => $data{zip_post},
    country  => $data{country},
    phone    => $data{phone},
    email    => $data{email},
    for_what => $data{for_what},
    program  => $data{program},
    note     => $data{note},
    amount_disp => commify($data{total}),
    req_mmc_id    => $data{id},
    req_mmc_code  => $code,
    signed        => $data{signed},
    quest_email   => $data{quest_email},
    tbl_py_desc   => $data{tbl_py_desc},
);

$stash{stripe_payment} = stripe_payment(
    name        => $data{program},
    description => "Registration for $data{first} $data{last}",
    amount      => $data{total},
    metadata    => { code => $code },
    email       => $data{email},
);

Template->new(
    INTERPOLATE => 1,
)->process(
    "req_pay.tt2",
    \%stash,
);
