#!/usr/bin/env perl
use strict;
use warnings;

use CGI;
my $q = CGI->new();
print $q->header();
use CGI::Carp qw/fatalsToBrowser/;
use lib '.';
use Template;

sub commify {
    my ($n) = @_;

    $n = reverse $n;
    $n =~ s{(\d\d\d)(?=\d)(?!\d*\.)}{$1,}gmsx;
    $n = scalar reverse $n;
    return $n;
}
my $code = $q->param('code');
if (! -f "/var/Reg/req_mmc_sent/$code") {
    print "Something is wrong with $code.\n";
    exit;
}
my $href = do "/var/Reg/req_mmc_sent/$code";
my %data = %$href;

my %stash = (
    payment_for => "Payment for MMC Program '$data{program}'",
    amount   => $data{total},
    first    => $data{first},
    last     => $data{last},
    addr     => $data{addr},
    city     => $data{city},
    state    => $data{st_prov},
    zip      => $data{zip_post},
    country  => $data{country},
    phone    => $data{phone},
    email    => $data{email},
    for_what => $data{for_what},
    program  => $data{program},
    note     => $data{note},
    amount_disp => commify($data{total}),
    req_mmc_id    => $data{id},
    req_mmc_code  => $code,
    signed        => $data{signed},
    quest_email   => $data{quest_email},
);

Template->new(
    INTERPOLATE => 1,
)->process(
    "req_mmc.tt2",
    \%stash,
);
