#!/usr/bin/env perl
use strict;
use warnings;

use CGI;
my $q = CGI->new();
print $q->header;
use CGI::Carp qw/
    fatalsToBrowser
/;
use Template;
my $tt = Template->new(
    INTERPOLATE => 1,
);
use lib '../lib';
use Util qw/
    trim
/;

my %P = $q->Vars();
if (! %P) {
    $tt->process(
        'sutra.tt2',
        {},
    );
    exit;
}

print <<"EOH";
<html>
<head>
<style>
body {
    margin: .5in;
    font-size: 17pt;
}
.sutra {
    margin-left: 5mm;
    font-size: 17pt;
}
.hr {
    margin-top: 4mm;
    margin-bottom: 4mm;
}
.date {
    display: block;
    margin-top: .2in;
    color: gray;
}
.hl {
    background-color: #FFFFA0;
}
</style>
</head>
<body>
EOH

use DBI;
my $dbh = DBI->connect(undef, "sahadev", "JonB")
    or die "cannot connect to database\n";

sub show {
    my ($t, $p) = @_;
    $t =~ s{($p)}{<span class=hl>$1</span>}xmsgi if $p;
    chomp $t;
    if (substr($t, 0, 1) eq '^') {
        $t =~ s{^\^}{<pre>};
        $t .= "</pre>";
    }
    $t =~ s{\n}{<br>\n}g;
    return <<"EOH";
<div class=sutra>
$t
</div>
EOH
}

sub valid_email {
    my ($em) = @_;
    return $em =~ m{\@};
}

if (exists $P{search}) {
    my $pattern = trim($P{pattern});
    if (! $pattern) {
        print "No pattern.";
        exit;
    }
    my $substring = $P{substring};
    my $start = "[[:<:]]";
    my $end   = "[[:>:]]";
    if ($substring) {
        $start = $end = '';
    }
    my $sth_search = $dbh->prepare(<<"EOS");
        SELECT content
          FROM sutra
         WHERE content regexp ?
      ORDER BY id
EOS
    $sth_search->execute("$start$pattern$end");
    my $n = 0;
    while (my $href = $sth_search->fetchrow_hashref) {
        ++$n;
        print show($href->{content}, $pattern);
        print "<hr class=hr width=370 align=left>\n";
    }
    if (! $n) {
        print "No sutra matches '$pattern'.";
    }
}
elsif (exists $P{sut_sub}) {
    my $email = trim($P{email});
    if (! $email) {
        print "Missing email address.";
        exit;
    }
    if (! valid_email($email)) {
        print "Invalid email address: $email";
        exit;
    }
    my $sth_addr_search = $dbh->prepare(<<"EOS");
        SELECT *
          FROM address
         WHERE email = ?
EOS
    $sth_addr_search->execute($email);
    if ($sth_addr_search->fetchrow_hashref()) {
        print "$email was already receiving the sutras.";
    }
    else {
        my $sth_addr_ins = $dbh->prepare(<<"EOS");
            INSERT
              INTO address
                   (email)
            VALUES (?)
EOS
        $sth_addr_ins->execute($email);
        print "$email will now receive the sutras.";
    }
}
elsif (exists $P{sut_unsub}) {
    my $email = trim($P{email});
    if (! $email) {
        print "Missing email address.";
        exit;
    }
    if (! valid_email($email)) {
        print "Invalid email address: $email";
        exit;
    }
    my $sth_addr_search = $dbh->prepare(<<"EOS");
        SELECT *
          FROM address
         WHERE email = ?
EOS
    $sth_addr_search->execute($email);
    if (! $sth_addr_search->fetchrow_hashref()) {
        print "$email is <i>not</i> receiving the sutras."
    }
    else {
        my $sth_addr_del = $dbh->prepare(<<"EOS");
            DELETE
              FROM address
             WHERE email = ?
EOS
        $sth_addr_del->execute($email);
        print "$email will no longer receive the sutras."; }
}
elsif (exists $P{show_all}) {
    my $sth_search = $dbh->prepare(<<"EOS");
        SELECT content
          FROM sutra
      ORDER BY id
EOS
    $sth_search->execute();
    while (my $href = $sth_search->fetchrow_hashref) {
        print show($href->{content});
        print "<hr class=hr width=370 align=left>\n";
    }
}
elsif (exists $P{rand_sut}) {
    # choose random sutra
    my @pics = <../root/static/images/sutra_pics/*>;
    my $pic = $pics[ rand @pics ];
    $pic =~ s{.*/}{}xms;
    my $sth_rand_sut = $dbh->prepare(<<'EOS');
        SELECT content
          FROM sutra
      ORDER BY RAND()
         LIMIT 1;
EOS
    $sth_rand_sut->execute();
    my $href = $sth_rand_sut->fetchrow_hashref();
    my $t = show($href->{content});
    print <<"EOH";
<table>
<tr>
<td>
<img src='/static/images/sutra_pics/$pic' border=3>
</td>
<td>
$t
</td>
</tr>
</table>
EOH
}
