Talks with Babaji

in /etc/nginx/sites-available:
    https://akash2.mountmadonna.org/talks
    redirects to
    https://akash2.mountmadonna.org/static/talks/index.html

See all here: https://akash.mountmadonna.org/talks

Search for term
    popup help - 's pat', insensitive, click on q&a to see in context

Note: Files in static/talks are generated by:

    cgi-bin/gen_talks
