#!/usr/bin/perl
use strict;
use warnings;
my $then = time - 3*30*24*60*60;
while (my $f = <*.txt>) {
    my $t = (stat($f))[9];
    printf "%30s %s", $f, scalar(localtime($t));
    if ($t > $then) {
        print " keep\n";
    }
    else {
        print " archive\n";
        rename $f, "older/$f";
    }
}
